# Generated by Django 4.1.3 on 2023-02-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='data',
            field=models.DateTimeField(default='2022-01-01 01:00:00 +00:00'),
        ),
        migrations.AlterField(
            model_name='retiradas',
            name='data',
            field=models.DateTimeField(default='2022-01-01 01:00:00 +00:00'),
        ),
    ]
