# Generated by Django 4.1.3 on 2023-01-14 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuario_options_usuario_idade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='fotoCinco',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='fotoQuatro',
        ),
    ]
