# Generated by Django 4.1.3 on 2023-01-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_produto_fotocinco_remove_produto_fotoquatro'),
    ]

    operations = [
        migrations.AddField(
            model_name='retiradas',
            name='nome',
            field=models.CharField(default=1, max_length=100, verbose_name='Usuário'),
            preserve_default=False,
        ),
    ]
