# Generated by Django 4.1.3 on 2023-01-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_retiradas_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiradas',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Usuário'),
        ),
    ]
