# Generated by Django 4.1.3 on 2023-01-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_retiradas_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidadeent', models.IntegerField(verbose_name='Quantidade')),
            ],
        ),
    ]
